-- AUTOMATICALLY GENERATED -- DO NOT EDIT!

ABILITY_INFO_BLOODELF1 = "- HUGE DICK.";
ABILITY_INFO_BLOODELF2 = "- POWERFUL CUMS.";
ABILITY_INFO_BLOODELF3 = "- POTENT GIRTH.";
ABILITY_INFO_BLOODELF4 = "- POWERFUL MUSK.";
ABILITY_INFO_DRAENEI1 = "- HUGE DICK.";
ABILITY_INFO_DRAENEI2 = "- POWERFUL CUMS.";
ABILITY_INFO_DRAENEI3 = "- POTENT GIRTH.";
ABILITY_INFO_DRAENEI4 = "- POWERFUL MUSK.";
ABILITY_INFO_DWARF1 = "- FARQUAD SE HA ENCENDIDO.";
ABILITY_INFO_DWARF2 = "- he gains fuego burrito.";
ABILITY_INFO_DWARF3 = "- puede pico goku a SS3J.";
ABILITY_INFO_DWARF4 = "- Treasure finding.";
ABILITY_INFO_DWARF5 = "- can go super sayan 4 combination.";
ABILITY_INFO_GNOME1 = "- FARQUAD.";
ABILITY_INFO_GNOME2 = "- Small but powerful";
ABILITY_INFO_GNOME3 = "- very good.";
ABILITY_INFO_GNOME4 = "- dick as big as body.";
ABILITY_INFO_HUMAN1 = "- Farmer who has had very enough of shrek.";
ABILITY_INFO_HUMAN2 = "- INHUMAN BEAST.";
ABILITY_INFO_HUMAN3 = "- NEVER TRUST AN ELF.";
ABILITY_INFO_HUMAN4 = "- not farquad.";
ABILITY_INFO_HUMAN5 = "- very good onion farmer.";
ABILITY_INFO_NIGHTELF1 = "- O fantasma e Lorde Farquaad .";
ABILITY_INFO_NIGHTELF2 = "- Spectral now ghost.";
ABILITY_INFO_NIGHTELF3 = "- as intellect as the universe.";
ABILITY_INFO_NIGHTELF4 = "- Farquad has new form.";
ABILITY_INFO_ORC1 = "- Shrek has BIG cums.";
ABILITY_INFO_ORC2 = "- 20meater onion scented dick.";
ABILITY_INFO_ORC3 = "- musk girth.";
ABILITY_INFO_ORC4 = "- Increased expertise with Maces.";
ABILITY_INFO_SCOURGE1 = "- gingerbread for huge girth.";
ABILITY_INFO_SCOURGE2 = "- cums bread.";
ABILITY_INFO_SCOURGE3 = "- potent musk.";
ABILITY_INFO_SCOURGE4 = "- war criminals only.";
ABILITY_INFO_TAUREN1 = "- Fast Donkey for quick attack.";
ABILITY_INFO_TAUREN2 = "- can only wear donkey clothes.";
ABILITY_INFO_TAUREN3 = "- female donkey VERY LARGE.";
ABILITY_INFO_TAUREN4 = "- very few layers not like onion.";
ABILITY_INFO_TROLL1 = "- puss in boots never.";
ABILITY_INFO_TROLL2 = "- u wanna be a furry u faget.";
ABILITY_INFO_TROLL3 = "- bet you suck cat dick.";
ABILITY_INFO_TROLL4 = "- very small.";
ABILITY_INFO_TROLL5 = "- like ur very small dick.";
ACCEPT = "Accept"; -- Generic "accept"
ACCOUNT_CREATE_FAILED = "Account creation failed";
ACCOUNT_CREATE_IN_PROGRESS = "Creating account";
ACCOUNT_CREATE_SUCCESS = "Account created";
ACCOUNT_CREATE_URL = "http://signup.worldofwarcraft.com";
ACCOUNT_MESSAGE_BODY_NO_READ_URL = "http://support.worldofwarcraft.com/accountmessaging/getMessageBodyUnread.xml"; -- used by the account messaging system to retrieve the body of a message without marking it read
ACCOUNT_MESSAGE_BODY_URL = "http://support.worldofwarcraft.com/accountmessaging/getMessageBody.xml"; -- used by the account messaging system to retrieve the body of a message. This marks the message as read
ACCOUNT_MESSAGE_BUTTON_READ = "Mark as read";
ACCOUNT_MESSAGE_HEADERS_URL = "http://support.worldofwarcraft.com/accountmessaging/getMessageHeaders.xml"; -- used for the account messaging to query the list of message headers
ACCOUNT_MESSAGE_READ_URL = "http://support.worldofwarcraft.com/accountmessaging/markMessageAsRead.xml"; -- used by the account messaging system to mark a message as read
ACCOUNT_NAME = "Account Name";
ACCOUNT_OPTIONS = "Account Options";
ADDONS = "AddOns";
ADDONS_OUT_OF_DATE = "You are running a new version of the game and have interface modifications which are out of date.  Disabling them is recommended.";
ADDON_BANNED = "Disabled";
ADDON_BANNED_TOOLTIP = "This addon has been disabled. You should install an updated version.";
ADDON_CORRUPT = "Corrupt";
ADDON_DEPENDENCIES = "Dependencies: ";
ADDON_DEP_BANNED = "Dependency banned";
ADDON_DEP_CORRUPT = "Dependency corrupt";
ADDON_DEP_DISABLED = "Dependency disabled";
ADDON_DEP_INCOMPATIBLE = "Dependency incompatible";
ADDON_DEP_INSECURE = "Dependency insecure";
ADDON_DEP_INTERFACE_VERSION = "Dependency out of date";
ADDON_DEP_MISSING = "Dependency missing";
ADDON_DISABLED = "Disabled";
ADDON_FORCE_LOAD = "Load out of date AddOns";
ADDON_INCOMPATIBLE = "Incompatible";
ADDON_INSECURE = "Insecure";
ADDON_INTERFACE_VERSION = "Out of date";
ADDON_LIST = "AddOn List";
ADDON_SECURE = "Secure";
ADDON_UPDATE_AVAILABLE = "New version is available\n";
AGI = "AGI"; -- G-15 Abbriviation for 'Agility'
ALL = "All";
ALLIANCE = "Alliance";
ALL_SETTINGS = "All Settings";
ALPHA_BUILD = "Alpha version";
AMBIENCE_VOLUME = "Ambience";
AMMO = "AMMO %d"; -- G-15 Abbriviation for 'Ammunition' as in Ammunition count (number of hunter bullets)
ANISOTROPIC = "Texture Filtering";
APPLY = "Apply";
ARM = "ARM"; -- G-15 Abbriviation for 'Armor'
ARMOR = "Armor";
ASSERTIONS_ENABLED_BUILD = "Release Assertions Enabled";
AUTH_ALREADY_LOGGING_IN = "Already Logging In";
AUTH_ALREADY_ONLINE = "This character is still logged on. If this character is not logged in and you continue to experience this issue for more than 15 minutes, please contact our Technical Support Department at wowtech@blizzard.com";
AUTH_BAD_SERVER_PROOF = "Server is not valid";
AUTH_BANNED = "This account has been banned for violating the Terms of Use Agreement - www.worldofwarcraft.com/termsofuse.shtml. Please contact our GM department via Email at wowaccountadmin@blizzard.com for more information.";
AUTH_BANNED_URL = "http://www.worldofwarcraft.com/termsofuse.shtml";
AUTH_BILLING_ERROR = "Billing system error";
AUTH_BILLING_EXPIRED = "Account billing has expired";
AUTH_DB_BUSY = "This session has timed out. Please try again at a later time or check the status of our WoW servers at www.worldofwarcraft.com/serverstatus";
AUTH_DB_BUSY_URL = "http://www.worldofwarcraft.com/serverstatus";
AUTH_FAILED = "Authentication failed";
AUTH_INCORRECT_PASSWORD = "Incorrect Password";
AUTH_LOCALE_MISMATCH = "Wrong client language";
AUTH_LOCKED_ENFORCED = "You have applied a lock to your account. You can change your locked status by calling your account lock phone number.";
AUTH_LOGIN_SERVER_NOT_FOUND = "Invalid Login Server";
AUTH_NO_TIME = "Your World of Warcraft subscription has expired. You will need to reactivate your account. To do so, please visit www.worldofwarcraft.com/account for more information.";
AUTH_NO_TIME_URL = "https://www.youtube.com/watch?v=68temYq3vVI";
AUTH_OK = "Authentication Successful";
AUTH_PARENTAL_CONTROL = "Access to this account is currently restricted by parental controls. You can change your control settings from your online account management.";
AUTH_PARENTAL_CONTROL_URL = "http://www.worldofwarcraft.com/account";
AUTH_REJECT = "Login unavailable - Please contact Technical Support at WoWTech@Blizzard.com";
AUTH_SERVER_SHUTTING_DOWN = "Server Shutting Down";
AUTH_SESSION_EXPIRED = "Session Expired";
AUTH_SUSPENDED = "This account has been temporarily suspended for violating the Terms of Use Agreement - www.worldofwarcraft.com/termsofuse.shtml. Please contact our GM department via Email at wowaccountadmin@blizzard.com for more information.";
AUTH_SUSPENDED_URL = "http://www.worldofwarcraft.com/termsofuse.shtml";
AUTH_SYSTEM_ERROR = "System Error";
AUTH_UNAVAILABLE = "System unavailable - Please try again later";
AUTH_UNKNOWN_ACCOUNT = "Unknown account";
AUTH_VERSION_MISMATCH = "Wrong client version";
AUTH_WAIT_QUEUE = "Position in Queue: %d";
AVAILABLE_CLASSES = "Available Classes";
BACK = "Back"; -- Generic "back"
BAG_SLOTS = "SLOTS %d"; -- G-15 Number of free bag slots
BATTLEFIELD_ALERT = "You are eligible to enter %s You will be removed from the queue in %s"; -- G-15
BETA_BUILD = "Beta";
BF_DEATHS = "Deaths"; -- G-15 Number of Deaths
BF_HONOR_KILLS = "Honorable Kills"; -- G-15 Number of kills
BF_HONOR_POINTS = "hnr"; -- G-15 Amount of Honor
BF_KILLBLOWS = "Killing Blows"; -- G-15 Killing blows
BF_RANK = "Rank"; -- G-15
BILLING_FIXED_IGR = "You are currently using a fixed IGR plan. Your personal time will not be deducted. The IGR plan will expire in %s.";
BILLING_FIXED_LASTDAY = "Your fixed plan account will expire in less than a day. Please go to the billing pages and purchase another plan.";
BILLING_FREE_TIME_EXPIRE = "Free account is about to expire. Once expired, you will be disconnected.\nThe remaining time is %s.";
BILLING_GAMEROOM_EXPIRE = "IGR account in use is about to expire. Once expired, you may get disconnected.\nPlease contact the manager on duty in your IGR.";
BILLING_HAS_FALLBACK_PAYMENT = "There may be additional time on your account from other payment plans.";
BILLING_IGR_USAGE = "You are currently using an IGR usage plan. Your personal time will not be deducted.";
BILLING_IGR_USAGE_TIME_LEFT_30_MINS = "This IGR usage plan has 30 minutes or less of play time left on it.";
BILLING_TEXT1 = "You are using a subscription to play this account.  You will be notified when you have one day or less on your account.";
BILLING_TEXT2 = "You are currently in your free trial period and will not be charged.";
BILLING_TEXT3 = "You are using a personal fixed plan.  Your plan will expire in %s.";
BILLING_TEXT4 = "You are now using your personal time to play this account.  You currently have %d minutes left on the current subscription.  You will be notified 30 minutes before you will run out of time.";
BILLING_TIME_LEFT_30_MINS = "You currently have 30 minutes or less left on your account.  If you have not already done so, please go to the billing pages and purchase more time.";
BILLING_TIME_LEFT_DAYS = "You have %d days of play time remaining.";
BILLING_TIME_LEFT_LAST_DAY = "Your play time will expire in less than 1 day.";
BLIZZ_DISCLAIMER = "Copyright 2004-2009  Blizzard Entertainment. All Rights Reserved.";
BLOCK = "BLOCK %.2f"; -- G-15
BLOODELF_DISABLED = "Blood Elf\nRequires The Burning Crusade";
BONUS_DAMAGE = "B.DMG %d"; -- G-15 Abbriviation for Bonus Damage
BONUS_HEALING = "B.HEAL %d"; -- G-15 Abbriviation for Bonus Healing
BURNING_CRUSADE = "The Burning Crusade";
CALCULATING = "Calculating...";
CANCEL = "Cancel"; -- Generic "cancel"
CANCEL_RESET = "Cancel Reset";
CANCEL_RESET_SETTINGS = "Are you sure you want to cancel resetting user options the next time you login?";
CATEGORY_DESCRIPTION = "Realm Category";
CATEGORY_DESCRIPTION_TEXT = "A realm category refers to its geographical location. Players should generally choose the realm that is closest to them. This ensures the lowest amount of latency and provides the best possible game experience.";
CHANGE = "Change";
CHANGED_OPTIONS_WARNING_TITLE = "NOTE:";
CHANGE_REALM = "Change Realm";
CHARACTER_CREATE_ACCEPT = "Accept";
CHARACTER_NAME = "Character Name";
CHARACTER_SELECT_INFO = "Level %d %s";
CHARACTER_SELECT_INFO_GHOST = "Level %d %s (Ghost)";
CHAR_CREATE_ACCOUNT_LIMIT = "You already have the maximum number of characters allowed on this account.";
CHAR_CREATE_CHARACTER_IN_GUILD = "Faction change failed, character in guild.";
CHAR_CREATE_DISABLED = "Character creation on this realm is currently disabled. Please try again at a later date or create a character on a different realm.";
CHAR_CREATE_ERROR = "Error creating character";
CHAR_CREATE_EXPANSION = "Implying this race will ever be finished and playable";
CHAR_CREATE_EXPANSION_CLASS = "Implying this class will ever be finished and playable";
CHAR_CREATE_FAILED = "Character creation failed";
CHAR_CREATE_INVALID_NAME = "Invalid character name";
CHAR_CREATE_IN_PROGRESS = "Creating character";
CHAR_CREATE_LEVEL_REQUIREMENT = "You must have an existing character of at least level 55 on any realm to create a Death Knight.";
CHAR_CREATE_NAME_IN_USE = "That name is unavailable";
CHAR_CREATE_ONLY_EXISTING = "Only players who already have characters on this realm are currently allowed to create characters.";
CHAR_CREATE_PVP_TEAMS_VIOLATION = "You cannot have both a Horde and an Alliance character on the same PvP server";
CHAR_CREATE_SERVER_LIMIT = "You already have the maximum number of characters allowed on this realm.";
CHAR_CREATE_SERVER_QUEUE = "This server is currently queued and new character creation is temporarily disabled. Please try again during off peak hours.";
CHAR_CREATE_SUCCESS = "Character created";
CHAR_CREATE_UNIQUE_CLASS_LIMIT = "You may only have one Death Knight Hero Class character on this realm.";
CHAR_CREATE_UNKNOWN = "Unknown error";
CHAR_CUSTOMIZATION0_DESC = "Gender";
CHAR_CUSTOMIZATION1_DESC = "Skin Color";
CHAR_CUSTOMIZATION2_DESC = "Face";
CHAR_CUSTOMIZATION3_DESC = "Hair Style";
CHAR_CUSTOMIZATION4_DESC = "Hair Color";
CHAR_CUSTOMIZATION5_DESC = "Facial Hair";
CHAR_CUSTOMIZATION6_DESC = "Outfit";
CHAR_CUSTOMIZE_FAILED = "Could not customize character.";
CHAR_DECLINE_FAILED = "Character name declension failed";
CHAR_DECLINE_IN_PROGRESS = "Updating Character...";
CHAR_DELETE_FAILED = "Character deletion failed";
CHAR_DELETE_FAILED_ARENA_CAPTAIN = "This character is an Arena Captain and cannot be deleted until the rank is transfered to another character.";
CHAR_DELETE_FAILED_GUILD_LEADER = "This character is a Guild Master and cannot be deleted until the rank is transfered to another character.";
CHAR_DELETE_FAILED_LOCKED_FOR_TRANSFER = "You cannot log in until the character update process you recently initiated is complete.  "; -- Modified to be more generic for PCNC and character restore.  from "Your character is currently locked as part of the paid character transfer process."
CHAR_DELETE_IN_PROGRESS = "Deleting character";
CHAR_DELETE_SUCCESS = "Character deleted";
CHAR_FACTION_CHANGE_ARENA_LEADER = "You may not change factions while still the captain of an arena team.";
CHAR_FACTION_CHANGE_CHOOSE_RACE = "You must change your race.";
CHAR_FACTION_CHANGE_DELETE_MAIL = "Please remove all mail before changing factions.";
CHAR_FACTION_CHANGE_FAILED = "Could not change faction for character.";
CHAR_FACTION_CHANGE_RACECLASS_RESTRICTED = "This race and class combination is restricted from the race change service.";
CHAR_FACTION_CHANGE_STILL_IN_ARENA = "You may not change factions while still a member of an arena team.";
CHAR_FACTION_CHANGE_STILL_IN_GUILD = "You may not change factions while still a member of a guild.";
CHAR_LIST_FAILED = "Error retrieving character list";
CHAR_LIST_RETRIEVED = "Character list retrieved";
CHAR_LIST_RETRIEVING = "Retrieving character list";
CHAR_LOGIN_DISABLED = "Login for that race, class, or character is currently disabled.";
CHAR_LOGIN_DUPLICATE_CHARACTER = "A character with that name already exists";
CHAR_LOGIN_FAILED = "Login failed";
CHAR_LOGIN_IN_PROGRESS = "Entering the World of Warcraft";
CHAR_LOGIN_LOCKED_BY_BILLING = "Character locked.  Contact Billing for more information.";
CHAR_LOGIN_LOCKED_FOR_TRANSFER = "You cannot log in until the character update process you recently initiated is complete. ";
CHAR_LOGIN_NO_CHARACTER = "Character not found"; -- Most likely moved by migration tool but still in server cache
CHAR_LOGIN_NO_INSTANCES = "No instance servers are available";
CHAR_LOGIN_NO_WORLD = "World server is down";
CHAR_LOGIN_SUCCESS = "Login successful";
CHAR_NAME_DECLENSION_DOESNT_MATCH_BASE_NAME = "Your declensions must match your original name.";
CHAR_NAME_FAILURE = "Invalid character name";
CHAR_NAME_INVALID_APOSTROPHE = "You cannot use an apostrophe as the first or last character of your name";
CHAR_NAME_INVALID_CHARACTER = "Names can only contain letters";
CHAR_NAME_INVALID_SPACE = "You cannot use a space as the first or last character of your name";
CHAR_NAME_MIXED_LANGUAGES = "Names must contain only one language";
CHAR_NAME_MULTIPLE_APOSTROPHES = "You can only have one apostrophe";
CHAR_NAME_NO_NAME = "Enter a name for your character";
CHAR_NAME_PROFANE = "That name contains mature language";
CHAR_NAME_RESERVED = "That name is unavailable";
CHAR_NAME_RUSSIAN_CONSECUTIVE_SILENT_CHARACTERS = "Can not have two silent symbols in a row."; -- This error only displays in Russian, so the english version doesn't matter. RUSSION LOCALIZATION - should rewrite as appropriate
CHAR_NAME_RUSSIAN_SILENT_CHARACTER_AT_BEGINNING_OR_END = "Silent characters are now allowed at the beginning or end of a name."; -- This error only displays in Russian, so the english version doesn't matter. RUSSION LOCALIZATION - should rewrite as appropriate
CHAR_NAME_THREE_CONSECUTIVE = "You cannot use the same letter three times consecutively";
CHAR_NAME_TOO_LONG = "Names must be no more than 12 characters";
CHAR_NAME_TOO_SHORT = "Names must be at least 2 characters";
CHAR_RENAME_DESCRIPTION = "Your name has been flagged for rename";
CHAR_RENAME_FAILED = "Character rename failed";
CHAR_RENAME_INSTRUCTIONS = "Please enter a new name";
CHAR_RENAME_IN_PROGRESS = "Renaming Character...";
CHOOSE_CLASS = "Choose your class:";
CHOOSE_GENDER = "Choose your gender:";
CHOOSE_LOCATION = "Choose your preferred location:";
CHOOSE_LOCATION_DESCRIPTION = "(for best results choose the region closest to you)";
CHOOSE_RACE = "Choose your race:";
CHOOSE_REALM_STYLE = "Choose your realm style:";
CINEMATICS = "Cinematics";
CINEMATIC_SUBTITLES = "Cinematic Subtitles";
CLASS = "Class"; -- -- Generic class label
CLASS_DEATHKNIGHT = "        Death knights are highly powerful, malevolent, runeblade-wielding champions of the Scourge. They are infamous for sowing disease and decay in their adversaries, smiting them down with devastating strikes, then raising the fallen as loyal minions. Their ability to focus and change the style of their runic powers makes them frighteningly powerful opponents to any who challenge them.";
CLASS_DEATHKNIGHT_FEMALE = "        Death knights are highly powerful, malevolent, runeblade-wielding champions of the Scourge. They are infamous for sowing disease and decay in their adversaries, smiting them down with devastating strikes, then raising the fallen as loyal minions. Their ability to focus and change the style of their runic powers makes them frighteningly powerful opponents to any who challenge them.";
CLASS_DRUID = "        Druids live in a state of unparalleled union with nature. Tightly bound to the plant and animal kingdoms, they are natural shapeshifters, and so they know firsthand the abuse visited on their wild brethren. In consequence, despite their numbers, druids tend to be wary, reclusive, and difficult to spot. Few outsiders have plumbed the depths of their secrets.";
CLASS_DRUID_FEMALE = "        Druids live in a state of unparalleled union with nature. Tightly bound to the plant and animal kingdoms, they are natural shapeshifters, and so they know firsthand the abuse visited on their wild brethren. In consequence, despite their numbers, druids tend to be wary, reclusive, and difficult to spot. Few outsiders have plumbed the depths of their secrets.";
CLASS_HUNTER = "        Hunters know the uncharted places of the world. Gifted with a deep empathy for all life, they have an uncanny knack for befriending wild animals and taming them as pets. In addition, hunters can use their finely honed senses to become master trackers. Wherever hunters go, they fight back the ravages of sickness, exploitation, and industrialization.";
CLASS_HUNTER_FEMALE = "        Hunters know the uncharted places of the world. Gifted with a deep empathy for all life, they have an uncanny knack for befriending wild animals and taming them as pets. In addition, hunters can use their finely honed senses to become master trackers. Wherever hunters go, they fight back the ravages of sickness, exploitation, and industrialization.";
CLASS_MAGE = "        Magi are wizards of immense knowledge and skill. Their obvious physical frailty is deceptive, for they can call upon the cosmic energies of the Twisting Nether. Rarely do magi engage in melee combat. Instead, they prefer to attack from a distance, hurling powerful bolts of frost and flame at their unsuspecting enemies.";
CLASS_MAGE_FEMALE = "        Magi are wizards of immense knowledge and skill. Their obvious physical frailty is deceptive, for they can call upon the cosmic energies of the Twisting Nether. Rarely do magi engage in melee combat. Instead, they prefer to attack from a distance, hurling powerful bolts of frost and flame at their unsuspecting enemies.";
CLASS_PALADIN = "        Paladins are champions who call upon the Light to heal wounds and combat evil. The draenei employed such holy warriors for millennia before arriving on Azeroth to find like-minded souls among the Alliance. Recently blood elves, too, began wielding paladin abilities. Yet these elves, having little in common with their counterparts, must bend the Light to their will.";
CLASS_PALADIN_FEMALE = "        Paladins are champions who call upon the Light to heal wounds and combat evil. The draenei employed such holy warriors for millennia before arriving on Azeroth to find like-minded souls among the Alliance. Recently blood elves, too, began wielding paladin abilities. Yet these elves, having little in common with their counterparts, must bend the Light to their will.";
CLASS_PRIEST = "        Priests guide the spiritual destiny of their people. Through their unique insight into the mind, they are able to shape an individual's beliefs, whether to inspire or terrify, soothe or dominate, heal or harm. Just as the heart can hold both darkness and light, priests wield powers of creation and devastation by channeling the potent forces underlying faith.";
CLASS_PRIEST_FEMALE = "        Priests guide the spiritual destiny of their people. Through their unique insight into the mind, they are able to shape an individual's beliefs, whether to inspire or terrify, soothe or dominate, heal or harm. Just as the heart can hold both darkness and light, priests wield powers of creation and devastation by channeling the potent forces underlying faith.";
CLASS_ROGUE = "        Rogues are most successful when their deeds never come to light. Fond of poisons and silent projectile weapons, rogues rely on a blend of stealth and minor mysticism. Usually in the employ of rich nobles or local governments, the rogue redistributes wealth or eliminates designated targets. A rogue's allegiance lasts only as long as the latest contract.";
CLASS_ROGUE_FEMALE = "        Rogues are most successful when their deeds never come to light. Fond of poisons and silent projectile weapons, rogues rely on a blend of stealth and minor mysticism. Usually in the employ of rich nobles or local governments, the rogue redistributes wealth or eliminates designated targets. A rogue's allegiance lasts only as long as the latest contract.";
CLASS_SHAMAN = "        Shaman commune directly with the elements. Their combination of wisdom and resilience makes them ideal as tribal advisors and leaders. In battle the shaman use totems and spells to manipulate the elements and provoke other fighters to untold heights of rage and might. Shaman exemplify the primal bond between the savage races and their environment.";
CLASS_SHAMAN_FEMALE = "        Shaman commune directly with the elements. Their combination of wisdom and resilience makes them ideal as tribal advisors and leaders. In battle the shaman use totems and spells to manipulate the elements and provoke other fighters to untold heights of rage and might. Shaman exemplify the primal bond between the savage races and their environment.";
CLASS_WARLOCK = "        Warlocks are the bane of all life. Empowered by demonic blood, they can inflict great torment upon their foes. To replenish the dreadful energy their spells expend, warlocks drain vitality from their victims. The warlock can also summon and control terrifying demonic entities. Still, warlocks are feared above all else for their singular wickedness and cruelty.";
CLASS_WARLOCK_FEMALE = "        Warlocks are the bane of all life. Empowered by demonic blood, they can inflict great torment upon their foes. To replenish the dreadful energy their spells expend, warlocks drain vitality from their victims. The warlock can also summon and control terrifying demonic entities. Still, warlocks are feared above all else for their singular wickedness and cruelty.";
CLASS_WARRIOR = "        Warriors train constantly and strive for perfection in armed combat. Though they come from all walks of life, they are united by their singular commitment to engage in glorious battle. Many warriors serve as mercenary soldiers, while others become adventurers and danger-seeking fortune hunters. A typical warrior is strong, tough, and exceptionally violent.";
CLASS_WARRIOR_FEMALE = "        Warriors train constantly and strive for perfection in armed combat. Though they come from all walks of life, they are united by their singular commitment to engage in glorious battle. Many warriors serve as mercenary soldiers, while others become adventurers and danger-seeking fortune hunters. A typical warrior is strong, tough, and exceptionally violent.";
CLEAR = "Clear"; -- Generic 'Clear' button label
CLEARMATRIX = "Clear"; -- 'Clear' button label for Matrix Card
CLICK_TO_LAUNCH_ADDON_URL = "Click to launch addon website\n";
CLIENT_ACCOUNT_MISMATCH_BC = "<html><body><p>Your account is authorized for the Burning Crusade expansion, but the computer you are playing on does not contain Burning Crusade data. To play on this machine with this account, you must install the Burning Crusade. Additional data is available at:<a href='http://www.worldofwarcraft.com/burningcrusade/download/'>www.worldofwarcraft.com/burningcrusade/download/</a></p></body></html>";
CLIENT_ACCOUNT_MISMATCH_LK = "<html><body><p>Your account is authorized for the Wrath of the Lich King expansion, but the computer you are playing on does not contain Wrath of the Lich King data. To play on this machine with this account, you must install the Wrath of the Lich King. Additional data is available at:<a href=\"http://www.worldofwarcraft.com/lichking/download/\">www.worldofwarcraft.com/lichking/download/</a></p></body></html>";
CLIENT_CONVERTED_TEXT = "Thank you for buying World of Warcraft.  Please click the restart button to begin downloading the full version of World of Warcraft.";
CLIENT_CONVERTED_TITLE = "Welcome to the World of Warcraft.";
CLIENT_RESTART_ALERT = "Some of your settings will not take effect until you restart the game.";
CLIENT_TRIAL = "<html><body><p>Your account is a full retail account, and is not compatible with the World of Warcraft Trial version. Please install the retail version of World of Warcraft. If you need more help, see <a href='http://www.worldofwarcraft.com/support/trial/'>www.worldofwarcraft.com/support/trial/</a></p></body></html>";
CLOSE = "Close";
COMMUNITY_SITE = "Community Site";
COMMUNITY_URL = "https://ivy.paheal.net/_images/f50dd618d021ffd121cf4bbaadccce86/807014%20-%20Donkey%20Shrek%20Shrek_%28series%29.jpg";
CONFIGURE_MODS_FOR = "Configure AddOns For:";
CONFIRM_CHAR_DELETE = "Do you want to delete\n|cffffffff%s   Level %d   %s|r?";
CONFIRM_CHAR_DELETE_INSTRUCTIONS = "Type \"DELETE\" into the field to confirm.";
CONFIRM_COMPLETE_EXPENSIVE_QUEST = "Completing this quest requires spending the following amount of money. Do you still want to complete the quest?";
CONFIRM_DISABLE_ADDONS = "You will need to re-enable your modifications once you install updated versions.  Are you sure you want to disable them?\n\n|cffffffffYou can re-enable them by using the \"Addons\" button in the lower left.|r";
CONFIRM_LAUNCH_ADDON_URL = "Clicking \"Okay\" will take you out of the game and open the following link in a web browser:\n%s";
CONFIRM_LOAD_ADDONS = "The game may not work correctly unless you have updated all your modifications.  Are you sure you want to try to load them?\n\n|cffffffffChanges can be made by using the \"Addons\" button in the lower left.|r";
CONFIRM_PCC = "Are you sure you are done customizing your character?";
CONFIRM_PFC = "Are you sure you are done changing your character?";
CONFIRM_RESET_SETTINGS = "Do you want to reset all settings to their defaults? This will immediately apply all settings.";
CONFIRM_TEMP = "Are you sure you are done?";
CONNECTION_HELP_FRAME_TITLE = "Connection Help";
CONTEST_FRAME_TITLE = "Contest Rules";
CONTEST_NOTICE = "The contest rules have changed. Please scroll down and review the changes before accepting the agreement.";
CREATE_ACCOUNT = "Create Account";
CREATE_CHARACTER = "Create Character";
CREATE_NEW_CHARACTER = "Create New Character";
CREDITS = "Credits";
CREDITS_WOW_BC = "Burning Crusade Credits";
CREDITS_WOW_CLASSIC = "World of Warcraft Credits";
CREDITS_WOW_LK = "Wrath of the Lich King Credits";
CRIT = "CRIT"; -- G-15 Abbriviation for 'Critical' as in Critical strike chance (melee)
CSTATUS_AUTHENTICATING = "Authenticating";
CSTATUS_CONNECTING = "Connecting to server...";
CSTATUS_NEGOTIATING_SECURITY = "Negotiating security";
CSTATUS_NEGOTIATION_COMPLETE = "Security negotiation complete";
CSTATUS_NEGOTIATION_FAILED = "Security negotiation failed";
CURRENT_SETTINGS = "These Settings";
CUSTOM = "Custom"; -- Video detail levels - custom
CUSTOMIZE_CHARACTER = "Customize character:";
DAYS_ABBR = "|4Day:Days;";
DEATHKNIGHT_DISABLED = "Death Knight\nRequires Wrath of the Lich King\nand a level 55 character";
DEATH_EFFECT = "Death Effect";
DEBUG_BUILD = "Debug";
DECLENSION_SET = "%s of %s";
DECLINE = "Decline"; -- Generic decline
DEFAULTS = "Defaults";
DEFENSE = "DEF %d"; -- G-15 Abbribiation for Defense
DELETE_CHARACTER = "Delete Character";
DELETE_CONFIRM_STRING = "DELETE";
DEPTH_CONVERGENCE = "Screen Depth";
DESKTOP_GAMMA = "Use desktop gamma";
DISABLE_ADDONS = "Disable";
DISABLE_ALL_ADDONS = "Disable All";
DISCONNECTED = "You have been disconnected from the server.";
DISPLAY = "Display";
DMG = "DMG"; -- G-15 Abbriviation for 'Damage'
DODGE = "DODGE %.2f"; -- G-15 Dodge
DONE = "Done";
DOWNLOADING_UPDATE = "Downloading Update";
DOWNLOAD_SUCCESSFUL = "Patch Required";
DOWNLOAD_SUCCESSFUL_TEXT = "Press the restart button below to exit World of\nWarcraft and download the patch.";
DPS = "DPS"; -- G-15 Abbriviation for 'Damage Per Second'
DRAENEI_DISABLED = "Draenei\nRequires The Burning Crusade";
DURABILITY = "DURA %d"; -- G-15 Abbriviation for durability
EFFECTS_LABEL = "Effects";
EFFECTS_SUBTEXT = "These controls allow you to modify specific detail levels for many game elements and effects.";
EMAIL_ADDRESS = "E-Mail Address";
ENABLED_FOR_SOME = "This addon is only enabled for some characters.";
ENABLE_ALL_ADDONS = "Enable All";
ENABLE_AMBIENCE = "Ambient Sounds";
ENABLE_BGSOUND = "Sound in Background";
ENABLE_DSP_EFFECTS = "Death Knight Voices";
ENABLE_EMOTE_SOUNDS = "Emote Sounds";
ENABLE_ERROR_SPEECH = "Error Speech";
ENABLE_HARDWARE = "Use Hardware";
ENABLE_MUSIC = "Music";
ENABLE_MUSIC_LOOPING = "Loop Music";
ENABLE_PET_SOUNDS = "Enable Pet Sounds";
ENABLE_REVERB = "Enable Reverb";
ENABLE_SOFTWARE_HRTF = "Headphone Mode";
ENABLE_SOUND = "Enable Sound";
ENABLE_SOUNDFX = "Sound Effects";
ENABLE_SOUND_AT_CHARACTER = "Sound at Character";
ENABLE_STEREO_VIDEO = "Enable Stereo Video";
ENTER_AUTHCODE_INFO = "Enter the generated digital code.";
ENTER_AUTHCODE_TITLE = "Authenticator Code";
ENTER_PIN_NUMBER = "Enter Your PIN";
ENTER_WORLD = "Enter World";
ENVIRONMENT_DETAIL = "Environment Detail";
ENVIRONMENT_LABEL = "Environment";
ENVIRONMENT_SUBTEXT = "These options control the ranges and levels of detail used to draw effects and objects in the game environment.";
EULA_FRAME_TITLE = "End User License Agreement";
EULA_NOTICE = "The End User License Agreement has changed. Please scroll down and review the changes before accepting the agreement.";
EXIT_GAME = "Exit Game";
EYE_SEPARATION = "Depth Amount";
FACIAL_HAIR_EARRINGS = "Earrings";
FACIAL_HAIR_FEATURES = "Features";
FACIAL_HAIR_HAIR = "Hair";
FACIAL_HAIR_HORNS = "Horn Style";
FACIAL_HAIR_MARKINGS = "Markings";
FACIAL_HAIR_NORMAL = "Facial Hair";
FACIAL_HAIR_PIERCINGS = "Piercings";
FACIAL_HAIR_TUSKS = "Tusks";
FACTION = "Faction"; -- -- Generic Faction label
FACTION_INFO_ALLIANCE = "        The Alliance consists of five races: the noble humans, the adventurous dwarves, the enigmatic night elves, the ingenious gnomes, and the honorable draenei. Bound by a loathing for all things demonic, they fight to restore order in this war-torn world.";
FACTION_INFO_HORDE = "        Five races comprise the Horde: the brutal orcs, the shadowy undead, the spiritual tauren, the quick-witted trolls, and the driven blood elves. Beset by enemies on all sides, these outcasts have forged a union they hope will ensure their mutual survival.";
FAR = "Far";
FARCLIP = "View Distance";
FEMALE = "Female";
FIX_LAG = "Reduce Input Lag";
FRIENDS = "Friends";
FULL_SCREEN_GLOW = "Full-Screen Glow Effect";
GAMETYPE_NORMAL = "Normal";
GAMETYPE_PVE = "Normal";
GAMETYPE_PVE_TEXT = "These realms allow you focus on adventuring and fighting monsters while allowing you to fight other players at your own discretion.";
GAMETYPE_PVP = "Player Versus Player  |cffff0000(PVP)|r";
GAMETYPE_PVP_TEXT = "These realms allow you to focus on player combat; you are always at risk of being attacked by opposing players except in starting areas and cities.";
GAMETYPE_RP = "Roleplaying |cff00ff00(RP)|r";
GAMETYPE_RPPVP = "Roleplaying PVP |cffff0000(RPPVP)|r";
GAMETYPE_RPPVP_TEXT = "These realms have strict naming conventions and behavior rules for players interested in immersing themselves as a character in a fantasy-based world.  They also focus on player combat; you are always at risk of being attacked by opposing players except in starting areas and cities.";
GAMETYPE_RP_TEXT = "These realms have strict naming conventions and behavior rules for players interested in immersing themselves as a character in a fantasy-based world.";
GAME_SERVER_LOGIN = "Logging in to game server";
GAME_SOUND_OUTPUT = "Game Sound Output";
GAME_UPDATES = "Game Updates";
GAMMA = "Gamma";
GENERAL_LABEL = "General";
GM_BUILD = "GM";
GROUND_DENSITY = "Ground Clutter Density";
GROUND_RADIUS = "Ground Clutter Radius";
HAIR_HORNS_COLOR = "Horn Color";
HAIR_HORNS_STYLE = "Horn Style";
HAIR_NORMAL_COLOR = "Hair Color";
HAIR_NORMAL_STYLE = "Hair Style";
HARDWARE = "Hardware";
HARDWARE_CURSOR = "Hardware Cursor";
HARDWARE_SURVEY_AGREE = "I consent";
HARDWARE_SURVEY_DISAGREE = "I don't consent";
HARDWARE_SURVEY_TITLE = "Hardware Survey Notification";
HELP = "Help";
HERTZ = "Hz";
HIGH = "High"; -- High level of something
HIT = "HIT"; -- G-15
HORDE = "Horde";
HOURS_ABBR = "|4Hr:Hrs;";
IDLE_LOGOUT_WARNING = "You will be logged out soon";
INT = "INT"; -- G-15 Abbrivation for 'Intellect'
LATEST_AGREEMENTS_URL = "http://launcher.worldofwarcraft.com/legal/agreements.mpq";
LATEST_EULA_URL = "http://launcher.worldofwarcraft.com/legal/eula.htm";
LATEST_TERMINATION_WITHOUT_NOTICE_URL = "http://launcher.worldofwarcraft.com/legal/notice.htm";
LATEST_TOS_URL = "http://launcher.worldofwarcraft.com/legal/tos.htm";
LAUNCH_FAILED = "Could not launch World of Warcraft.";
LAUNCH_MAC_SYSTEM_REQUIRED = "World of Warcraft requires Mac OS X version %s.";
LAUNCH_QUICKTIME_REQUIRED = "World of Warcraft requires QuickTime version %s.";
LAUNCH_USE_SOFTWARE_UPDATE = "Please use Software Update in System Preferences to upgrade your system software."; -- This string is Mac specific.  The updater is called "Sofware Update"
LAUNCH_VIDEO_CARD_UNSUPPORTED = "World of Warcraft cannot run on your video card.";
LEVEL = "Level"; -- Level of a monster, character or item
LOAD_ADDONS = "Load Anyway";
LOAD_FULL = "Full";
LOAD_HIGH = "High";
LOAD_LOW = "Low";
LOAD_MEDIUM = "Medium";
LOAD_NEW = "New";
LOAD_RECOMMENDED = "New Players";
LOGIN = "Login";
LOGIN_ACCOUNT_CONVERTED = "This account is now attached to a Battle.net account. Please log in with your Battle.net account email address (example: john.doe@blizzard.com) and password."; -- This message is displayed if a user attempts to log in using a WoW account that has been attached to a Blizzard account.
LOGIN_ALREADYONLINE = "This account is already logged into World of Warcraft.  Please check the spelling and try again.";
LOGIN_ANTI_INDULGENCE = "Your game account is locked by anti-indulgence controls.";
LOGIN_AUTH_OUTAGE = "<html><body><p align=\"CENTER\">The login server is currently busy. Please try again later. If the problem persists, please contact Technical Support at: <a href=\"http://us.blizzard.com/support/index.xml?gameId=11&amp;rootCategoryId=2316\">http://us.blizzard.com/support/index.xml?gameId=11&amp;rootCategoryId=2316</a></p></body></html>";
LOGIN_BADVERSION = "<html><body><p align=\"CENTER\">Unable to validate game version.  This may be caused by file corruption or the interference of another program.  Please visit <a href=\"http://us.blizzard.com/support/article.xml?articleId=21031\">http://us.blizzard.com/support/article.xml?articleId=21031</a> for more information and possible solutions to this issue.</p></body></html>";
LOGIN_BAD_SERVER_PROOF = "<html><body><p align=\"CENTER\">You are connecting to an invalid game server. Please contact Technical Support for assistance at: <a href=\"http://us.blizzard.com/support/index.xml?gameId=11&amp;rootCategoryId=2316\">http://us.blizzard.com/support/index.xml?gameId=11&amp;rootCategoryId=2316</a></p></body></html>";
LOGIN_BAD_SERVER_RECODE_PROOF = "Recode Proof Bad";
LOGIN_BANNED = "<html><body><p align=\"CENTER\">This World of Warcraft account has been closed and is no longer available for use.  Please go to <a href=\"http://www.worldofwarcraft.com/misc/banned.html\">http://www.worldofwarcraft.com/misc/banned.html</a> for further information.</p></body></html>"; -- This is the error message players get when trying to log in with a banned account.
LOGIN_CHARGEBACK = "<html><body><p align=\"CENTER\">This World of Warcraft account has been temporary closed due to a chargeback on its subscription.  Please refer to this <a href=\"http://us.blizzard.com/support/article/chargeback\">http://us.blizzard.com/support/article/chargeback</a> for further information.</p></body></html>"; -- Players account was suspended due to a chargeback.
LOGIN_DBBUSY = "Could not log in to World of Warcraft at this time.  Please try again later.";
LOGIN_ENTER_NAME = "Please enter your account name.";
LOGIN_ENTER_PASSWORD = "Please enter your password.";
LOGIN_ERROR = "Error";
LOGIN_EXPIRED = "<html><body><p align=\"CENTER\">Your game account subscription has expired. Please visit <a href=\"http://www.worldofwarcraft.com/account\">www.worldofwarcraft.com/account</a> to purchase. more time.</p></body></html>";
LOGIN_FAILED = "<html><body><p align=\"CENTER\">Unable to connect. Please try again later. If the problem persists, please contact technical support at: <a href=\"http://us.blizzard.com/support/index.xml?gameId=11&amp;rootCategoryId=2316\">http://us.blizzard.com/support/index.xml?gameId=11&amp;rootCategoryId=2316</a></p></body></html>";
LOGIN_GAME_ACCOUNT_LOCKED = "<html><body><p align=\"CENTER\">Access to your account has been temporarily disabled. Please contact support for more information at: <a href=\"https://www.worldofwarcraft.com/account/account-error.html\">https://www.worldofwarcraft.com/account/account-error.html</a></p></body></html>";
LOGIN_IGR_WITHOUT_BNET = "<html><body><p align=\"CENTER\">In order to log in to World of Warcraft using IGR time, this World of Warcraft account must first be merged with a Battle.net account. Please visit <a href=\"http://us.battle.net/\">http://us.battle.net/</a> to merge this account.</p></body></html>";
LOGIN_INCORRECT_PASSWORD = "Incorrect Password";
LOGIN_INVALID_CHALLENGE_MESSAGE = "Invalid Challenge";
LOGIN_INVALID_PROOF_MESSAGE = "Invalid Proof Message";
LOGIN_INVALID_RECODE_MESSAGE = "Invalid Recode Message";
LOGIN_LOCALE_MISMATCH = "Wrong client language";
LOGIN_LOCKED_ENFORCED = "You have applied a lock to your account. You can change your locked status by calling your account lock phone number.";
LOGIN_MALFORMED_ACCOUNT_NAME = "<html><body><p align=\"CENTER\">The information you have entered is not valid.  Please check the spelling of the account name and password.  If you need help in retrieving a lost or stolen password and account, see <a href=\"http://www.worldofwarcraft.com/loginsupport\">www.worldofwarcraft.com/loginsupport</a> for more information.</p></body></html>";
LOGIN_NOTIME = "<html><body><p align=\"CENTER\">You have used up your prepaid time for this account. Please visit <a href=\"http://www.worldofwarcraft.com/account\">www.worldofwarcraft.com/account</a> to purchase more to continue playing.</p></body></html>";
LOGIN_NO_BATTLENET_APPLICATION = "<html><body><p align=\"CENTER\">There was an error loging in. Please try again later. If the problem persists, please contact Technical Support at: <a href=\"http://us.blizzard.com/support/index.xml?gameId=11&amp;rootCategoryId=2316\">http://us.blizzard.com/support/index.xml?gameId=11&amp;rootCategoryId=2316</a></p></body></html>";
LOGIN_NO_BATTLENET_MANAGER = "<html><body><p align=\"CENTER\">There was an error loging in. Please try again later. If the problem persists, please contact Technical Support at: <a href=\"http://us.blizzard.com/support/index.xml?gameId=11&amp;rootCategoryId=2316\">http://us.blizzard.com/support/index.xml?gameId=11&amp;rootCategoryId=2316</a></p></body></html>";
LOGIN_NO_GAME_ACCOUNT = "There is no World of Warcraft game account associated with this Battle.net account.";
LOGIN_PARENTALCONTROL = "Access to this account is currently restricted by parental controls. You can change your control settings from your online account management.";
LOGIN_SERVER_DOWN = "Login Server Down";
LOGIN_SRP_ERROR = "Authentication Error";
LOGIN_STATE_AUTHENTICATED = "Success!";
LOGIN_STATE_AUTHENTICATING = "Authenticating";
LOGIN_STATE_CHECKINGVERSIONS = "Validating Version";
LOGIN_STATE_CONNECTING = "Connecting";
LOGIN_STATE_DOWNLOADFILE = "Downloading";
LOGIN_STATE_HANDSHAKING = "Handshaking";
LOGIN_STATE_INITIALIZED = "Initialized";
LOGIN_STATE_SURVEY = "Submitting non-personal system specification";
LOGIN_SUSPENDED = "<html><body><p align=\"CENTER\">This World of Warcraft account has been temporarily suspended. Please go to <a href=\"http://www.worldofwarcraft.com/misc/banned.html\">http://www.worldofwarcraft.com/misc/banned.html</a> for further information.</p></body></html>"; -- This is the error message a player receives when trying to log in with a suspended account.
LOGIN_TOO_FAST = "You have too many login attempts. Please try again in a few minutes."; -- To prevent login spamming, this error is shown if the player quickly tries to login many times. Player must wait a little while before trying again.
LOGIN_TRIAL_EXPIRED = "<html><body><p align=\"CENTER\">Your trial subscription has expired. Please visit <a href=\"http://www.worldofwarcraft.com/account\">www.worldofwarcraft.com/account</a> to upgrade your account.</p></body></html>";
LOGIN_UNKNOWN_ACCOUNT = "<html><body><p align=\"CENTER\">The information you have entered is not valid.  Please check the spelling of the account name and password.  If you need help in retrieving a lost or stolen password and account, see <a href=\"http://www.worldofwarcraft.com/loginsupport\">www.worldofwarcraft.com/loginsupport</a> for more information.</p></body></html>";
LOGIN_UNKNOWN_ACCOUNT_CALL = "Call customer service";
LOGIN_UNKNOWN_ACCOUNT_PIN = "<html><body><p align=\"CENTER\">The information you have entered is not valid.  Please check the spelling of the account name, password, and PIN.  If you need help in retrieving a lost or stolen password, account, or PIN see <a href=\"http://www.worldofwarcraft.com/loginsupport\">www.worldofwarcraft.com/loginsupport</a> for more information.</p></body></html>";
LOGIN_UNLOCKABLE_LOCK = "This account has been locked but can be unlocked.";
LOGIN_USE_GRUNT = "Please use your World of Warcraft account name and password instead of your Battle.net account.";
LOW = "Low"; -- Low level of something
MALE = "Male";
MANAGE_ACCOUNT = "Manage Account";
MASTER_VOLUME = "Master Volume";
MELEE_CRIT = "CRIT %.2f"; -- G-15 Abbriviation for Critical (as in melee critical strike)
MENU_ABOUT = "About World of Warcraft...";
MENU_EDIT = "Edit";
MENU_EDIT_COPY = "Copy";
MENU_EDIT_CUT = "Cut";
MENU_EDIT_PASTE = "Paste";
MENU_EDIT_SELECT_ALL = "Select All";
MENU_EDIT_UNDO = "Undo";
MENU_SWITCH_TO_FULLSCREEN = "Switch to Full Screen Mode";
MINUTES = "%d |4min:mins;";
MINUTES_ABBR = "|4Min:Mins;";
MISCELLANEOUS = "Miscellaneous";
MULTISAMPLE = "Multisampling";
MULTISAMPLING_FORMAT_STRING = "%d-bit color %d-bit depth %dx multisample";
MUSIC_VOLUME = "Music";
NAME = "Name";
NAME_AND_REST_STATE = "%s - %s"; -- Name - rest state
NEAR = "Near";
NEWS = "News";
NEW_REALM = "New";
NO = "No";
NONE_CAPS = "NONE"; -- "None", in all capitals
NORMAL_BUILD = "Version";
OKAY = "Okay"; -- Generic "okay"
OPTIONS = "Options";
OPTIONS_BRIGHTNESS = "Brightness";
OPTIONS_SHADERS = "Shaders";
OPTION_RESTART_REQUIREMENT = "Requires game restart to take effect.";
OPTION_STEREO_CONVERGENCE = "Changes the 3D depth of the screen.";
OPTION_STEREO_SEPARATION = "Changes the amount of separation created by 3D depth.";
OPTION_TOOLTIP_AMBIENCE_VOLUME = "Adjusts the ambient sound volume.";
OPTION_TOOLTIP_AMBIENT_VOLUME = "Adjusts the ambient sound volume.";
OPTION_TOOLTIP_ANISOTROPIC = "Increases texture sharpness, particularly for textures viewed at an angle.  Decrease to improve performance.";
OPTION_TOOLTIP_CINEMATIC_SUBTITLES = "Enables subtitles during the intro cinematic.";
OPTION_TOOLTIP_DEATH_EFFECT = "Uncheck to disable glowing effect while in ghost form. Disabling this can sometimes improve performance.";
OPTION_TOOLTIP_DESKTOP_GAMMA = "Use the same gamma settings as your desktop.";
OPTION_TOOLTIP_ENABLE_AMBIENCE = "Enable ambient sounds.";
OPTION_TOOLTIP_ENABLE_BGSOUND = "Enable to allow sounds to play even when World of Warcraft is in the background.";
OPTION_TOOLTIP_ENABLE_DSP_EFFECTS = "Enables special voice modulation effects for Death Knights.";
OPTION_TOOLTIP_ENABLE_EMOTE_SOUNDS = "Toggles emote sounds on and off.";
OPTION_TOOLTIP_ENABLE_ERROR_SPEECH = "Enables speech from errors (e.g. \"Target out of range\").";
OPTION_TOOLTIP_ENABLE_HARDWARE = "Enables the use of hardware for 3D sound management. This may alter your sound performance.";
OPTION_TOOLTIP_ENABLE_MUSIC = "Enable background music.";
OPTION_TOOLTIP_ENABLE_MUSIC_LOOPING = "Enable to continuously play background music.";
OPTION_TOOLTIP_ENABLE_PET_SOUNDS = "Toggles pet idle and aggro sounds on and off.";
OPTION_TOOLTIP_ENABLE_REVERB = "Enables reverb sound effects.  This will affect performance.";
OPTION_TOOLTIP_ENABLE_SOFTWARE_HRTF = "Enables software emulation for headphone surround sound.";
OPTION_TOOLTIP_ENABLE_SOUND = "Enables or disables all sound.";
OPTION_TOOLTIP_ENABLE_SOUNDFX = "Enables or disables game sound effects.";
OPTION_TOOLTIP_ENABLE_SOUND_AT_CHARACTER = "Listen to sound from the character's point of view rather than the camera.";
OPTION_TOOLTIP_ENABLE_STEREO_VIDEO = "Enables stereoscopic (3D) video.";
OPTION_TOOLTIP_ENVIRONMENT_DETAIL = "Controls how far you can see objects. Decrease to improve performance.";
OPTION_TOOLTIP_FARCLIP = "Changes how far you can see. Decreasing this may greatly improve performance.";
OPTION_TOOLTIP_FIX_LAG = "Enabling this reduces user interface lag, but may drastically reduce frame rates.";
OPTION_TOOLTIP_FULL_SCREEN_GLOW = "Enables a full screen effect that softens edges and lighting. Disabling this can sometimes improve performance.";
OPTION_TOOLTIP_GAMMA = "Controls the brightness of the game. Increase brightness until you can clearly see all 21 levels of gray bars below.";
OPTION_TOOLTIP_GROUND_DENSITY = "Controls the number of ground clutter items, like grass and foliage.  Decrease to improve performance.";
OPTION_TOOLTIP_GROUND_RADIUS = "Controls the draw distance of ground clutter items like grass and foliage.  Decrease to improve performance.";
OPTION_TOOLTIP_HARDWARE_CURSOR = "Enable this option for a more responsive cursor unless you have cursor problems.";
OPTION_TOOLTIP_MASTER_VOLUME = "Adjusts the master sound volume.";
OPTION_TOOLTIP_MULTISAMPLING = "Increase multisampling to smooth out model edges. Increasing multisampling can severely reduce performance.";
OPTION_TOOLTIP_MUSIC_VOLUME = "Adjusts the background music volume.";
OPTION_TOOLTIP_PARTICLE_DENSITY = "Controls the number of particles used in effects caused by spells, fires, etc. Decrease to improve performance.";
OPTION_TOOLTIP_PLAYER_DETAIL = "Controls the resolution of player textures. Decreasing this may slightly improve performance.";
OPTION_TOOLTIP_PROJECTED_TEXTURES = "Enables the projecting of textures to the environment. Disabling this may greatly improve performance.";
OPTION_TOOLTIP_SHADOW_QUALITY = "Controls the quality of rendered character and environment shadows. Decrease to improve performance.";
OPTION_TOOLTIP_SOUND_CHANNELS = "Changes the number of active software sound channels.";
OPTION_TOOLTIP_SOUND_OUTPUT = "Selects where you would like to hear your game sounds.";
OPTION_TOOLTIP_SOUND_QUALITY = "Adjusts the quality of game sounds.\nDecrease to improve performance.";
OPTION_TOOLTIP_SOUND_VOLUME = "Adjusts the sound effect volume.";
OPTION_TOOLTIP_SPELL_DETAIL = "Controls the detail level of spell effects.  Decrease to improve performance.";
OPTION_TOOLTIP_STEREO_HARDWARE_CURSOR = "While enabling this option may improve performance, the 3D cursor functionality will not work with it enabled.";
OPTION_TOOLTIP_TERRAIN_HIGHLIGHTS = "Enables specular highlights on terrain. Disabling this can sometimes improve performance.";
OPTION_TOOLTIP_TERRAIN_TEXTURE = "Sets the rate at which one type of terrain blends to another.";
OPTION_TOOLTIP_TEXTURE_DETAIL = "Controls the level of all texture detail. Decreasing this may slightly improve performance.";
OPTION_TOOLTIP_TRIPLE_BUFFER = "Enables triple buffering of frames when vertical sync is enabled. Selecting triple buffering may even out frame rate spikes, but may also cause slight input lag.";
OPTION_TOOLTIP_USE_REFRESH = "Changes the monitor refresh rates. Higher rates flicker less.";
OPTION_TOOLTIP_USE_RESOLUTION = "Changes the screen resolution of the game. Decrease to improve performance.";
OPTION_TOOLTIP_VERTICAL_SYNC = "Synchronizes your framerate to some fraction of your monitor's refresh rate. Enable this if you see excessive screen tearing in game.";
OPTION_TOOLTIP_WEATHER_DETAIL = "Controls the intensity of weather effects.  Decrease to improve performance.";
OPTION_TOOLTIP_WINDOWED_MAXIMIZED = "Check to maximize window and remove borders.";
OPTION_TOOLTIP_WINDOWED_MODE = "Check to play in a non-fullscreen window.\n\nIf this is checked the game will use your desktop gamma and you will not be able to adjust it via the slider below.";
OPTION_TOOLTIP_WINDOW_LOCK = "Enable this to prevent resizing the game window.";
OPTION_TOOLTIP_WORLD_LOD = "Check this to enable dynamic reduction of terrain polygon detail.  Check to increase performance.";
OPTION_UI_DEPTH = "Changes the base depth of the UI.";
OUTBID_ON_SHORT = "Outbid on %s";
PAID_CHARACTER_CUSTOMIZE_TOOLTIP = "Click to customize your character";
PAID_FACTION_CHANGE_TOOLTIP = "Click to change your character's faction";
PARRY = "PARRY %.2f"; -- G-15
PARTICLE_DENSITY = "Particle Density";
PASSWORD = "Account Password";
PATCH_FAILED_DISK_FULL = "There is not enough disk space available to download the patch.  Please make %d megabytes available and then try again.  Please note that additional space will be required to apply the patch.";
PATCH_FAILED_MESSAGE = "Failed to apply patch. Please try again later.  If this problem persists you may need to reinstall or contact technical support.";
PENETRATION = "PENET %d"; -- G-15 Abbriviation for Spell Penetration
PIXEL_SHADERS = "Special Effects";
PLAYBACK = "Playback";
PLAYER_DETAIL = "Player Textures";
POWER = "PWR"; -- G-15 Abbriviation for Power
PROJECTED_TEXTURES = "Projected Textures";
PTR_BUILD = "PTR"; -- Public Test Realm abbreviation. Used for the client version type.
PVP_PARENTHESES = "(PVP)";
QUEUE_NAME_TIME_LEFT = "%s is Full\nPosition in queue: %d\nEstimated time: %d min";
QUEUE_NAME_TIME_LEFT_SECONDS = "%s is Full\nPosition in queue: %d\nEstimated time: < 1 minute";
QUEUE_NAME_TIME_LEFT_UNKNOWN = "%s is Full\nPosition in queue: %d\nEstimated time: Calculating...";
QUEUE_TIME_LEFT = "Realm is Full\nPosition in queue: %d\nEstimated time: %d min";
QUEUE_TIME_LEFT_SECONDS = "Realm is Full\nPosition in queue: %d\nEstimated time: < 1 minute";
QUEUE_TIME_LEFT_UNKNOWN = "Realm is Full\nPosition in queue: %d\nEstimated time: Calculating...";
QUIT = "Quit";
RACE = "Race"; -- -- Generic race label
RACE_INFO_BLOODELF = "        big gay lol.";
RACE_INFO_BLOODELF_FEMALE = "        big gay lol.";
RACE_INFO_DRAENEI = "        big gay lol.";
RACE_INFO_DRAENEI_FEMALE = "        big gay lol.";
RACE_INFO_DWARF = "        Farquad desbloqueó su verdadero potencial y se fue SS3 Blacno, de esta forma es más fuerte que Goku y Vegito combinados, Piccolo lo adora al igual que el resto del equipo Z, está iluminado.";
RACE_INFO_DWARF_FEMALE = "        Farquad desbloqueó su verdadero potencial y se fue SS3 Blacno, de esta forma es más fuerte que Goku y Vegito combinados, Piccolo lo adora al igual que el resto del equipo Z, está iluminado.";
RACE_INFO_GNOME = "        Farquaad is the leader of Duloc, supreme gentleman ruler of the lands, his girth is long and wide and reaches the unwashed masses, truly a gentle and benevolent ruler";
RACE_INFO_GNOME_FEMALE = "        Farquaad is the leader of Duloc, supreme gentleman ruler of the lands, his girth is long and wide and reaches the unwashed masses, truly a gentle and benevolent ruler";
RACE_INFO_HUMAN = "        Farmers are ready to kick the non humans out and save duloc, garithos was right";
RACE_INFO_HUMAN_FEMALE = "        Farmers are ready to kick the non humans out and save duloc, garithos was right";
RACE_INFO_NIGHTELF = "        Farquad got killed by cheating dragon hacks and now is ghost, he is enlightened in his own hubris and can literally posses people with his giant phantasmal cum spirit, a new step in farquad evolution";
RACE_INFO_NIGHTELF_FEMALE = "        Farquad got killed by cheating dragon hacks and now is ghost, he is enlightened in his own hubris and can literally posses people with his giant phantasmal cum spirit, a new step in farquad evolution";
RACE_INFO_ORC = "        Shrek is big bad and full of onions, he is angry at people in his swamp and willing to kick them out, with or without his errect throbbing member.";
RACE_INFO_ORC_FEMALE = "        Fiona is ogre but female so mostley useless, like shrek but less cool";
RACE_INFO_SCOURGE = "        Ginderbread man was baked by old lady, he is rude and crass and takes no shit, to bad this will never be finished because this is too much effort, even writing this is effort who reads thsi shit anyway.";
RACE_INFO_SCOURGE_FEMALE = "        Ginderbread man was baked by old lady, he is rude and crass and takes no shit, to bad this will never be finished because this is too much effort, even writing this is effort who reads thsi shit anyway.";
RACE_INFO_TAUREN = "        Donkey is shreks best friend and very fast horse, always talks a lot but very reliable when needed, capable of fucking dragons and gets that dragon clam wet, destroyer of dragon vaginas";
RACE_INFO_TAUREN_FEMALE = "        Dragon is donkeys fucksleeve, thanks based pixar for showing interracial relationships voiced between a grunting cockmagnet and eddie murphy is posspible";
RACE_INFO_TROLL = "        Cat men that are worgen reskins because lazy and we all know furries jack to this gay shit, im looking at you.";
RACE_INFO_TROLL_FEMALE = "        Cat men that are worgen reskins because lazy and we all know furries jack to this gay shit, im looking at you.";
RACIAL_ABILITIES = "Racial Abilities";
RANDOMIZE = "Randomize";
REALMLIST_NUMCHARACTERS_TOOLTIP = "The number of characters\nyou have created on this realm.";
REALMLIST_POPULATION_TOOLTIP = "\"Recommended\" realms will give you the best play experience.\n\"Full\" realms are the most crowded, and you will often\nexperience a wait time to play.";
REALMLIST_REALMNAME_TOOLTIP = "Make sure you check which realm your friends are playing on!";
REALMLIST_TYPE_TOOLTIP = "Normal = No special rules on this realm.\nPvP = Player versus Player.\nRP = Roleplaying realm.\nRPPvP = Player versus Player, Roleplaying realm.";
REALM_CHARACTERS = "Characters";
REALM_DESCRIPTION = "Choosing a Realm";
REALM_DESCRIPTION_TEXT = "A realm is a discrete game world that exists only for the players within it. You can interact with all the players in your realm, but not with players in other realms. You cannot move your characters between realms. Realms are differentiated by location and play style.";
REALM_DOWN = "Offline";
REALM_HELP_FRAME_TEXT = "This account is currently not flagged to participate in the tournament realms. For more information regarding the World of Warcraft Arena Tournament, please visit: %s.";
REALM_HELP_FRAME_TITLE = "Realms Unavailable"; -- Title for frame explaining why some users cannot connect to tournament realms
REALM_HELP_FRAME_URL = "<a href=\"http://www.worldofwarcraft.com/\">www.worldofwarcraft.com</a>"; -- URL where users can obtain information on different realm types
REALM_INFO_TEMPLATE = "%-32.32s %4d";
REALM_IS_FULL_WARNING = "You have selected a full server which can result in a wait to play. You should consider selecting a server with a low population.\n\nDo you really want to select this server?";
REALM_LIST_FAILED = "Unable to connect to realm list server";
REALM_LIST_INVALID = "Invalid realm list";
REALM_LIST_IN_PROGRESS = "Retrieving realm list";
REALM_LIST_REALM_NOT_FOUND = "The game server you have chosen is currently down.  Use the Change Realm button to choose another Realm.  Check www.worldofwarcraft.com/serverstatus for current server status.";
REALM_LIST_SUCCESS = "Realm list retrieved";
REALM_LOAD = "Population";
REALM_LOCKED = "Locked";
REALM_NAME = "Realm Name";
REALM_TYPE = "Type";
REALM_TYPE_LOCALE_WARNING = "You are trying to play on a realm with a different language.";
REALM_TYPE_TOURNAMENT_WARNING = "This account is currently not flagged to participate in the tournament realms.\n\nFor more information regarding the World of Warcraft Arena Tournament, please visit: www.worldofwarcraft.com.";
REFRESH_RATE = "Refresh";
REGEN = "REGEN %.0f"; -- G-15 Abbriviation for Mana Regeneration
RELEASE_BUILD = "Release";
RESET_SERVER_SETTINGS = "Are you sure you want to reset all user options to their defaults the next time you login?";
RESET_SETTINGS = "Reset User Options";
RESET_WARNING = "All user options will be reset the next time you log in!";
RESILIENCE = "RESIL %d"; -- G-15 Abbriviation for Resilience
RESOLUTION = "Resolution";
RESOLUTION_LABEL = "Resolution";
RESOLUTION_SUBTEXT = "These options allow you to change the size and detail in which your video hardware renders the game.";
RESPONSE_CANCELLED = "Cancelled";
RESPONSE_CONNECTED = "Connected";
RESPONSE_DISCONNECTED = "Disconnected from server";
RESPONSE_FAILED_TO_CONNECT = "Failed to connect.  Please be sure that your computer is currently connected to the internet, and that no security features on your system might be blocking traffic.  See www.blizzard.com/support/wow/ for more information.";
RESPONSE_FAILURE = "Failure";
RESPONSE_SUCCESS = "Success";
RESPONSE_VERSION_MISMATCH = "Wrong client version";
RESTART = "Restart";
RETURN_TO_LOGIN = "Return to Login";
RPPVP_PARENTHESES = "(RPPVP)";
RP_PARENTHESES = "(RP)";
RUSSIAN_DECLENSION = "Declensions";
RUSSIAN_DECLENSION_1 = "Genitive Case";
RUSSIAN_DECLENSION_2 = "Dative Case";
RUSSIAN_DECLENSION_3 = "Accusative Case";
RUSSIAN_DECLENSION_4 = "Instrumental Case";
RUSSIAN_DECLENSION_5 = "Prepositional Case";
RUSSIAN_DECLENSION_EXAMPLE_1 = "I always travel with %s.";
RUSSIAN_DECLENSION_EXAMPLE_2 = "First thing yesterday I bonked %s on the head.";
RUSSIAN_DECLENSION_EXAMPLE_3 = "Today I met %s again.";
RUSSIAN_DECLENSION_EXAMPLE_4 = "Now I am friends with %s.";
RUSSIAN_DECLENSION_EXAMPLE_5 = "Although I know nothing about %s.";
SAVE_ACCOUNT_NAME = "Remember Account Name";
SCANDLL_BUTTON_CONTINUEANYWAY = "Continue Anyway"; -- Caption of button to run WoW even though downloading Scan.dll failed
SCANDLL_BUTTON_MOREINFO = "More Info"; -- Caption of button to see more information on the web site about a hack or Trojan that was found
SCANDLL_MESSAGE_DOWNLOADING = "[TEMPORARY] Downloading Blizzard Scan"; -- Message shown while downloading Scan.dll
SCANDLL_MESSAGE_ERROR = "[TEMPORARY] |cFFFF0000Blizzard Scan failed to complete|r\n\nNEED WORDING"; -- Message to display when Scan.dll could not be loaded for some reason
SCANDLL_MESSAGE_HACK = "<html><body><p>\"%1$s\" has been detected on your computer. Running this program may compromise the security of your computer and jeopardize your ability to play World of Warcraft. It is highly advised that you correct this problem before playing the game.</p><p>For more information: <a href='%2$s'>Click Here</a></p></body></html>"; -- Message displayed when a hack is discovered by Scan.dll.  %s contains hack name
SCANDLL_MESSAGE_HACKFOUND_CONFIRM = "<html><body><p>As stated, \"%1$s\" has been detected on your computer. Running this program may compromise the security of your computer and jeopardize your ability to play World of Warcraft. It is highly advised that you correct this problem before playing the game.</p><p>For more information: <a href='%2$s'>Click Here</a></p></body></html>";
SCANDLL_MESSAGE_HACKNOCONTINUE = "<html><body><p>\"%1$s\" has been detected. This program may be a security risk and/or violate the Terms of Use for World of Warcraft. You must restart your computer and ensure that this program is not active in order to continue.</p><p>For more information: <a href='%2$s'>Click Here</a></p></body></html>";
SCANDLL_MESSAGE_SCANNING = "[TEMPORARY] Scanning for Trojans"; -- Message shown while running Scan.dll
SCANDLL_MESSAGE_TROJAN = "<html><body><p>\"%1$s\" has been detected on your computer. Running this program may compromise the security of your computer and jeopardize your ability to play World of Warcraft. It is highly advised that you correct this problem before playing the game.</p><p>For more information: <a href='%2$s'>Click Here</a></p></body></html>"; -- Message displayed when a Trojan is discovered by Scan.dll.  %s contains Trojan name
SCANDLL_MESSAGE_TROJANFOUND_CONFIRM = "<html><body><p>As stated, \"%1$s\" has been detected on your computer. Running this program may compromise the security of your computer and jeopardize your ability to play World of Warcraft. It is highly advised that you correct this problem before playing the game.</p><p>For more information: <a href='%2$s'>Click Here</a></p></body></html>";
SCANDLL_URL_HACK = "http://us.blizzard.com/support/article.xml?articleId=21583"; -- URL to which the user is sent when a hack is detected by Scan.dll
SCANDLL_URL_LAUNCHER_TXT = "http://us.scan.worldofwarcraft.com/update/Launcher.txt"; -- URL to use to download Launcher.txt
SCANDLL_URL_TROJAN = "http://us.blizzard.com/support/article.xml?articleId=21370"; -- URL to which the user is sent when a Trojan is detected by Scan.dll
SCANDLL_URL_WIN32_SCAN_DLL = "http://us.scan.worldofwarcraft.com/update/Scan.dll"; -- URL to use to download PC Scan.dll
SCANNING_NOTICE = "The scanning aggreement has changed. Please scroll down and review the changes before accepting the agreement.";
SCAN_FRAME_TITLE = "Scanning Agreement";
SECONDS = "%d |4sec:secs;";
SECONDS_ABBR = "|4Sec:Secs;";
SECURITYMATRIX_DIRECTIONS = "In order to complete logging into World of Warcraft you must enter values from your matrix card.";
SECURITYMATRIX_ENTER_CELL = "Enter the cell value |cFF00FF00%s%s|r then select OK. If you make a mistake, select Clear.";
SELECT_ACCOUNT = "Select an account";
SELECT_CHARACTER = "Select A Character";
SELECT_RACE = "Select your race";
SERVER_ALERT_BETA_URL = "http://beta.worldofwarcraft.com/alert";
SERVER_ALERT_BUTTON_TEXT = "More Info";
SERVER_ALERT_PTR_URL = "";
SERVER_ALERT_TITLE = "Breaking News";
SERVER_ALERT_URL = "http://launcher.worldofwarcraft.com/alert";
SERVER_DOWN = "Server down";
SERVER_SELECTION = "Realm Selection";
SERVER_SPLIT = "This realm has exceeded maximum capacity, and will be undergoing a realm split with players divided between two new realms. You will be able to select which of the two new realms you prefer up until |cffffffff%s|r when the split lockout occurs. If you do not make a selection, you will be assigned to one of the new realms. For more information, visit www.worldofwarcraft.com.\n\nPlease select your new realm preference below. You may change your selection at any time until the lockout date.";
SERVER_SPLIT_BUTTON = "Realm Split";
SERVER_SPLIT_CHOOSE_BY = "Choose by:";
SERVER_SPLIT_CURRENT_CHOICE = "Current Choice:\n%s";
SERVER_SPLIT_DONT_CHANGE = "Clear Choice";
SERVER_SPLIT_NOT_NOW = "Decide Later";
SERVER_SPLIT_PENDING = "Realm Split Pending...";
SERVER_SPLIT_REALM_CHOICE = "Your current choice is '|cffffffff%s|r'";
SERVER_SPLIT_SERVER_ONE = "Realm 1";
SERVER_SPLIT_SERVER_TWO = "Realm 2";
SHADOW_QUALITY = "Shadow Quality";
SHOW_LAUNCHER = "Show Launcher";
SKILLLINES = "Skill Lines";
SOUL_SHARD = "SHRDS %d"; -- G-15 Abbriviation for Soul Shards (warlock item)
SOUNDOPTIONS_MENU = "Sound";
SOUND_CHANNELS = "Sound Channels";
SOUND_LABEL = "Sound";
SOUND_QUALITY = "Sound Quality";
SOUND_SUBTEXT = "These options control sound hardware and the types and volumes of sounds within the game.";
SOUND_VOLUME = "Sound";
SPD = "SPD %d"; -- G-15 Abbriviation for Speed
SPEED = "SPD"; -- G-15 Abbriviation for the word Speed
SPELL_DETAIL = "Spell Detail";
SPI = "SPI"; -- G-15 Abbriviation for 'Spirit'
STA = "STA"; -- G-15 Abbriviation for 'Stamina'
STEREO_HARDWARE_CURSOR = "Hardware Cursor";
STEREO_VIDEO_LABEL = "Stereo";
STEREO_VIDEO_SUBTEXT = "These options allow you to change details having to do with stereoscopic (3D) viewing.";
STR = "STR"; -- G-15 Abbriviation for 'Strength'
STREAMING_BUILD = "Streaming"; -- Type of client where data isn't all installed at once
SUGGESTED_REALM_TEXT = "|cffffffffYou have been assigned to the|r %s |cffffffffRealm.|r";
SUGGEST_REALM = "Suggest Realm";
SYSTEM_DEFAULT = "System Default"; -- Dropdown menu item for the sound options menu - The default audio device
TECH_SUPPORT = "Tech Support";
TECH_SUPPORT_URL = "http://www.blizzard.com/support/wow/"; -- Tech support web address
TEMP_ARMOR = "- Cloth\n- Leather\n- Mail";
TEMP_SKILLS = "- Battle Cries\n- First Aid\n- War Shouts";
TEMP_WEAPON = "- Throwing\n- Axes\n- 2 - Hand Axes\n- Swords\n- 2 - Hand Swords\n- Maces\n- 2 - Hand Maces\n- Polearms\n- Bows";
TERMINATION_WITHOUT_NOTICE_FRAME_TITLE = "Termination of Service without Prior Notice";
TERMINATION_WITHOUT_NOTICE_NOTICE = "The Terms of Use have changed. Please scroll down and review the changes before accepting the agreement.";
TERRAIN_HIGHLIGHTS = "Specular Lighting";
TERRAIN_MIP = "Terrain Blending";
TEXTURE_DETAIL = "Texture Resolution";
TOS_ACCEPT = "Accept";
TOS_FRAME_TITLE = "Terms of Use";
TOS_NOTICE = "The Terms of Use have changed. Please scroll down and review the changes before accepting the agreement."; -- Notice when the TOS has changed and the player has to re-accept it
TRIAL_LOADING_MESSAGE = "|cffffd100Note:|r Since this is your first time playing this race, please wait while starting data is downloaded to your system. This may take a few minutes.";
TRIPLE_BUFFER = "Triple Buffering";
UI_DEPTH = "UI Depth";
UNKNOWN_ZONE = "Unknown Zone";
USE_ENGLISH_SPEECH_PACK = "Use English Speech Pack";
VERSION = "Version";
VERSION_TEMPLATE = "%s %s (%s) (%s)\n%s"; -- Version type(alpha, etc.), version number, internal number, build type(debug, release), date
VERTICAL_SYNC = "Vertical Sync";
VIDEOOPTIONS_MENU = "Video";
VIDEO_OPTIONS_RESET = "Your video settings have changed.";
VIDEO_QUALITY_LABEL1 = "Low";
VIDEO_QUALITY_LABEL2 = "Fair";
VIDEO_QUALITY_LABEL3 = "Good";
VIDEO_QUALITY_LABEL4 = "High";
VIDEO_QUALITY_LABEL5 = "Ultra";
VIDEO_QUALITY_LABEL6 = "Custom";
VIDEO_QUALITY_S = "Video Quality: %s"; -- Used with VIDEO_QUALITY_LABEL for video quality slider.
VIDEO_QUALITY_SUBTEXT1 = "These are the lowest recommended graphics settings for the game. These settings provide excellent performance.";
VIDEO_QUALITY_SUBTEXT2 = "Medium texture detail, short draw distance, low spell effect detail. These settings provide good performance.";
VIDEO_QUALITY_SUBTEXT3 = "High texture detail, medium draw distance, medium spell effect detail. These settings balance performance and quality.";
VIDEO_QUALITY_SUBTEXT4 = "High texture detail, farthest draw distance, high spell effect detail. These settings provide very high quality.";
VIDEO_QUALITY_SUBTEXT5 = "These settings provide the very best quality and should only be used on high-end systems.";
VIDEO_QUALITY_SUBTEXT6 = "Allows you to customize individual draw distances, detail levels, and effects. Performance and quality will vary by setting.";
VIEW_ALL_REALMS = "View Realm List";
VIRTUAL_KEYPAD_OKAY = "Okay"; -- for use in the virtual keypad
VOLUME = "Volume";
WEAPONS = "Weapons";
WEAPON_SKILL = "W.Skill %d"; -- G-15 Abbriviation for Weapon Skill
WEATHER_DETAIL = "Weather Intensity";
WEB_SITE = "WoW Website";
WHISPER_FROM = "Whisper from %s";
WIDESCREEN_TAG = "(Wide)";
WINDOWED_MAXIMIZED = "Maximized";
WINDOWED_MODE = "Windowed Mode";
WINDOW_LOCK = "Disable Resize";
WORLD_APPEARANCE = "World Appearance";
WORLD_LOD = "Level of Detail";
WORLD_OF_WARCRAFT = "World of Warcraft"; -- G-15
WOW_ACCOUNTS = "World of Warcraft Accounts";
WRATH_OF_THE_LICH_KING = "Wrath of the Lich King";
YES = "Yes";
